In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
dataset = pd.read_csv('cust_satisfaction.csv')
dataset.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0

In [3]:
dataset.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [4]:
dataset.dropna(inplace=True)

In [5]:
dataset.duplicated().sum()

np.int64(172)

In [6]:
dataset.drop_duplicates(inplace=True)

In [7]:
dataset.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0

In [8]:
dataset["Customer Type"].value_counts()

Customer Type
Loyal Customer       84517
disloyal Customer    18905
Name: count, dtype: int64

In [9]:
dataset['Gender'] = dataset['Gender'].map({"Male":1,"Female":0})
dataset['Customer Type'] = dataset['Customer Type'].map({"Loyal Customer":1,"Disloyal Customer":0})
dataset["Type of Travel"] = dataset["Type of Travel"].map({"Business travel":1,"Personal Travel":0})    
dataset["Class"] = dataset["Class"].map({"Business":1,"Eco":2,"Eco Plus":3})
dataset["satisfaction"] = dataset["satisfaction"].map({"satisfied":1,"neutral or dissatisfied":0})
dataset.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,1.0,0,3,0,13,460,5,4,5,25,18.0
1,1,NaN,1,1,0,25,235,1,3,1,1,6.0
2,0,1.0,1,1,1,26,1142,5,4,5,0,0.0
3,0,1.0,1,1,0,25,562,2,3,2,11,9.0
4,1,1.0,1,1,1,61,214,3,4,3,0,0.0

In [10]:
loyal_customer = dataset[dataset['Customer Type'] == 1].loc[0:2000]
disloyal_customer = dataset[dataset['Customer Type'] == 0]

In [11]:
balance_dataset = pd.concat([loyal_customer, disloyal_customer], axis=0)
balance_dataset.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,1.0,0,3,0,13,460,5,4,5,25,18.0
2,0,1.0,1,1,1,26,1142,5,4,5,0,0.0
3,0,1.0,1,1,0,25,562,2,3,2,11,9.0
4,1,1.0,1,1,1,61,214,3,4,3,0,0.0
5,0,1.0,0,2,0,26,1180,1,4,1,0,0.0

In [12]:
x = balance_dataset.drop(['Customer Type'], axis=1)
y = balance_dataset['Customer Type']

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_Scaled = scaler.fit_transform(x_train)
x_test_Scaled = scaler.transform(x_test)

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential()


model.add(Dense(68,activation = "relu",input_dim = x_train_Scaled.shape[1]))

model.add(Dense(32,activation = "relu"))
model.add(Dense(24,activation = "relu"))
model.add(Dense(16,activation = "relu"))

model.add(Dense(1,activation = "sigmoid"))

model.compile(loss = "binary_crossentropy",optimizer = "adam",metrics = ["accuracy"])
model.summary()

c:\Users\himek\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 68)             │           816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 24)             │           792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,233 (16.54 KB)

 Trainable params: 4,233 (16.54 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping  

early_stopping = EarlyStopping(  
    monitor="val_loss",
    patience=3,
    restore_best_weights=True  
)

history = model.fit(
    x_train_Scaled, y_train,
    epochs=50,
    batch_size=32,
    validation_data=(x_test_Scaled, y_test),  
    callbacks=[early_stopping]  
)

Epoch 1/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9822 - loss: 0.4169 - val_accuracy: 1.0000 - val_loss: 0.0200
Epoch 2/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0099 - val_accuracy: 1.0000 - val_loss: 0.0020
Epoch 3/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 1.0000 - val_loss: 0.0010
Epoch 4/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.9845e-04 - val_accuracy: 1.0000 - val_loss: 6.2041e-04
Epoch 5/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.1752e-04 - val_accuracy: 1.0000 - val_loss: 4.2018e-04
Epoch 6/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.5304e-04 - val_accuracy: 1.0000 - val_loss: 3.0384e-04
Epoch 7/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.2866e-04 - val_accuracy: 1.0000 - val_loss: 2.2847e-04
Epoch 8/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.8482e-04 - val_accuracy: 1.0000 - val_loss: 1.7783e-04
Epoch 9/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.4661e-04 - val_accuracy: 1.0000 - val_loss: 1.4285e-04
Epoch 10/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.2058e-04 - val_accuracy: 1.0000 - val_loss: 1.1751e-04
Epoch 11/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.0848e-04 - val_accuracy: 1.0000 - val_loss: 9.8137e-05
Epoch 12/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.9757e-05 - val_accuracy: 1.0000 - val_loss: 8.2611e-05
Epoch 13/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 8.0512e-05 - val_accuracy: 1.0000 - val_loss: 6.9955e-05
Epoch 14/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.8846e-05 - val_accuracy: 1.0000 - val_loss: 5.9644e-05
Epoch 15/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.5600e-05 - val_accuracy: 1.0000 - val_loss: 4.9889e-05
Epoch 16/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 4.6660e-05 - val_accuracy: 1.0000 - val_loss: 4.1411e-05
Epoch 17/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.6641e-05 - val_accuracy: 1.0000 - val_loss: 3.3454e-05
Epoch 18/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.9978e-05 - val_accuracy: 1.0000 - val_loss: 2.6650e-05
Epoch 19/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.2705e-05 - val_accuracy: 1.0000 - val_loss: 2.1249e-05
Epoch 20/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.7795e-05 - val_accuracy: 1.0000 - val_loss: 1.6747e-05
Epoch 21/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.4934e-05 - val_accuracy: 1.0000 - val_loss: 1.3104e-05
Epoch 22/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.3088e-05 - val_accuracy: 1.0000 - val_loss: 1.0458e-05
Epoch 23/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.0764e-05 - val_accuracy: 1.0000 - val_loss: 8.5697e-06
Epoch 24/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.1167e-06 - val_accuracy: 1.0000 - val_loss: 7.1199e-06
Epoch 25/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.7042e-06 - val_accuracy: 1.0000 - val_loss: 5.9181e-06
Epoch 26/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.2851e-06 - val_accuracy: 1.0000 - val_loss: 4.9896e-06
Epoch 27/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 4.2413e-06 - val_accuracy: 1.0000 - val_loss: 4.3015e-06
Epoch 28/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 4.4051e-06 - val_accuracy: 1.0000 - val_loss: 3.6692e-06
Epoch 29/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 3.1589e-06 - val_accuracy: 1.0000 - val_loss: 3.1785e-06
Epoch 30/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.2741e-06 - val_accuracy: 1.0000 - val_loss: 2.7875e-06
Epoch 31/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.6494e-06 - val_accuracy: 1.0000 - val_loss: 2.4667e-06
Epoch 32/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.8176e-06 - val_accuracy: 1.0000 - val_loss: 2.2015e-06
Epoch 33/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.1236e-06 - val_accuracy: 1.0000 - val_loss: 1.9577e-06
Epoch 34/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.8012e-06 - val_accuracy: 1.0000 - val_loss: 1.7725e-06
Epoch 35/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.6515e-06 - val_accuracy: 1.0000 - val_loss: 1.5923e-06
Epoch 36/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.5798e-06 - val_accuracy: 1.0000 - val_loss: 1.4408e-06
Epoch 37/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.3469e-06 - val_accuracy: 1.0000 - val_loss: 1.3151e-06
Epoch 38/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.0936e-06 - val_accuracy: 1.0000 - val_loss: 1.2037e-06
Epoch 39/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.1836e-06 - val_accuracy: 1.0000 - val_loss: 1.1031e-06
Epoch 40/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.0641e-06 - val_accuracy: 1.0000 - val_loss: 1.0169e-06
Epoch 41/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 9.2240e-07 - val_accuracy: 1.0000 - val_loss: 9.4018e-07
Epoch 42/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.8577e-07 - val_accuracy: 1.0000 - val_loss: 8.7220e-07
Epoch 43/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 9.0411e-07 - val_accuracy: 1.0000 - val_loss: 8.0537e-07
Epoch 44/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 8.3234e-07 - val_accuracy: 1.0000 - val_loss: 7.4971e-07
Epoch 45/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.2258e-07 - val_accuracy: 1.0000 - val_loss: 6.9993e-07
Epoch 46/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 6.5519e-07 - val_accuracy: 1.0000 - val_loss: 6.5283e-07
Epoch 47/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 6.0338e-07 - val_accuracy: 1.0000 - val_loss: 6.1093e-07
Epoch 48/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.9446e-07 - val_accuracy: 1.0000 - val_loss: 5.7097e-07
Epoch 49/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.1223e-07 - val_accuracy: 1.0000 - val_loss: 5.3690e-07
Epoch 50/50
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.4466e-07 - val_accuracy: 1.0000 - val_loss: 5.0483e-07